### PR TITLE
Add fswatch backend.

### PR DESCRIPTION
**Pull request by tsufeki**

### CODE REVIEW

**Comment by andig** [comment]
I think the README is wrong, missing one parameter:

	$monitor->on('all', function ($path, $isDir, $event) {

~~Then line 177 uses the wrong variable:~~

With these two changes its working on a quick check :)

**Comment by andig** [comment]
Also this can be simplified if you're targeting PHP 7:

        $this->fswatchCmd = isset($options['fswatch_cmd']) ? $options['fswatch_cmd'] : 'fswatch';

becomes

        $this->fswatchCmd = $options['fswatch_cmd'] ?? 'fswatch';

Sorry for the non-linked comments, offline at time of writing...

**Comment by andig** [comment]
Would it also make sense to emit an error in `handleBatch` if an unknown event is detected? 
Would also be cool to have the factory create the right watcher depending on OS (use `php_uname('s') === 'Darwin'`.

I guess you could also target `react/stream:1.0` in addition- that's what react/http is already doing.

**Comment by tsufeki** [comment]
I incorporated your comments, thanks.

I wonder if actually checking for existing executable in the factory (something like `if (shell_exec('which inotifywait 2>/dev/null')) {`) would be a good idea?

**Comment by andig** [comment]
> I wonder if actually checking for existing executable in the factory (something like if (shell_exec('which inotifywait 2>/dev/null')) {) would be a good idea?

Shouldn't it be possible to simply get the result from react child process? I haven't checked this though.

**Comment by andig** [comment]
Great, much appreciated!

**Pull request merged**
